# Generated by Django 6.1.1 on 2026-10-06 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeechangehistory',
            name='changed_by',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
