# Generated by Django 6.1.1 on 2026-10-06 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_employeechangehistory_changed_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeechangehistory',
            name='changed_by',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
