# Generated by Django 6.1.1 on 2026-10-07 04:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0003_alter_employeechangehistory_changed_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeesalaryhistory',
            name='idempotency_key',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
