# Generated by Django 6.1.1 on 2026-10-07 05:03

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0004_employeesalaryhistory_idempotency_key'),
    ]

    operations = [
        migrations.AddField(
            model_name='employeechangehistory',
            name='correlation_id',
            field=models.UUIDField(db_index=True, default=uuid.uuid4, editable=False),
        ),
    ]
